# Generated by Django 5.1.4 on 2026-08-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_add_inventory_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(blank=True, help_text="Small pill above the title, e.g. '✨ New Collection 2026'", max_length=100)),
                ('title', models.CharField(help_text="Main heading. Use ** around one word to highlight it, e.g. 'Refined **Style** for Men'", max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='One-line tagline below the title', max_length=300)),
                ('stat1_number', models.CharField(blank=True, help_text='e.g. 500+', max_length=20)),
                ('stat1_label', models.CharField(blank=True, help_text='e.g. Styles Available', max_length=60)),
                ('stat2_number', models.CharField(blank=True, help_text='e.g. 98%', max_length=20)),
                ('stat2_label', models.CharField(blank=True, help_text='e.g. Happy Clients', max_length=60)),
                ('stat3_number', models.CharField(blank=True, help_text='e.g. 1–2', max_length=20)),
                ('stat3_label', models.CharField(blank=True, help_text='e.g. Days Delivery', max_length=60)),
                ('btn1_text', models.CharField(blank=True, default='Explore Collection', max_length=80)),
                ('btn1_url', models.CharField(blank=True, default='/shop/', max_length=200)),
                ('btn2_text', models.CharField(blank=True, default='Our Story ↗', max_length=80)),
                ('btn2_url', models.CharField(blank=True, default='/about/', max_length=200)),
                ('image_url', models.URLField(blank=True, help_text='URL of the circle image (leave blank for emoji placeholder)', max_length=500, null=True)),
                ('circle_emoji', models.CharField(blank=True, default='👔', help_text='Emoji shown when no image URL is provided', max_length=10)),
                ('badge1_text', models.CharField(blank=True, help_text="Floating badge top-right, e.g. 'Premium Quality'", max_length=60)),
                ('badge2_text', models.CharField(blank=True, help_text="Floating badge bottom-left, e.g. 'New Arrivals'", max_length=60)),
                ('theme', models.CharField(choices=[('light', 'Light (cream background)'), ('dark', 'Dark (navy background)'), ('warm', 'Warm (tan background)'), ('custom', 'Custom (use bg_color field)')], default='light', help_text='Controls the slide background and text colour', max_length=10)),
                ('bg_color', models.CharField(blank=True, help_text="Custom CSS background value (only used when theme = Custom), e.g. '#1a1a2e' or 'linear-gradient(135deg,#0f1a2e,#1a2a4a)'", max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'id'],
            },
        ),
    ]
