# Generated by Django 5.1.4 on 2026-08-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image from your computer (JPEG, PNG, WebP)', null=True, upload_to='hero_slides/'),
        ),
    ]
