# Generated by Django 5.1.4 on 2026-08-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_heroslide_add_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='badge_bg',
            field=models.CharField(blank=True, help_text='Badge pill background, e.g. rgba(201,168,76,0.13)', max_length=60),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='badge_color',
            field=models.CharField(blank=True, help_text='Badge pill text color', max_length=30),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='bg_image',
            field=models.ImageField(blank=True, help_text='Upload a full-bleed background image (overrides bg_color when set)', null=True, upload_to='hero_slides/bg/'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='highlight_color',
            field=models.CharField(blank=True, help_text='Highlighted word color (default gold #C9A84C)', max_length=30),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='stat_color',
            field=models.CharField(blank=True, help_text='Stat numbers color (default gold)', max_length=30),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='stat_label_color',
            field=models.CharField(blank=True, help_text='Stat labels color', max_length=30),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_color',
            field=models.CharField(blank=True, help_text='Subtitle text color', max_length=30),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_color',
            field=models.CharField(blank=True, help_text='Title text color, e.g. #1a1a1a', max_length=30),
        ),
    ]
