# Generated by Django 5.1.4 on 2026-08-20 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_heroslide_colors_bgimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Gallery image for product detail page', upload_to='product_gallery/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=300)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Order in which images appear')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured/hero image for detail page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='shop.product')),
            ],
            options={
                'verbose_name_plural': 'Product Gallery Images',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
